name: Python application

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'master'
    paths-ignore:
      - '.github/workflows/**'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        cd .github/
        docker-compose run lms /openedx/requirements/eol-vof-xblock/.github/test.sh
